basePath: http://127.0.0.1:8090
host: localhost
info:
  contact:
    email: support@swagger.io
    name: yay
    url: http://www.swagger.io/support
  description: 招新网站api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: go-Recruitment
  version: "1.0"
paths: {}
swagger: "2.0"
